### ISSUE TITLE
Fluid Texture Color is missing (Contenttweaker)

### ISSUE THREAD

**Issue by Freebi85** [Kotori316/FluidTank#10]
Huhu ;-) ✌️ 

There is a little visual issue with Contenttweaker Fluids.

When i put a CT liquid in a Large Fluid Tank, than he has no color. (alwas stays white like steam)

In a Mekanism or Thermalexp. Tank it appears normal.

Freebi

**Comment by Kotori316** [comment]
Fixed in v3.1.
I used this ZenScript code, copied from https://crafttweaker.readthedocs.io/en/latest/#Mods/ContentTweaker/Vanilla/Creatable_Content/Fluid

``` java : sample
#loader contenttweaker

import mods.contenttweaker.VanillaFactory;
import mods.contenttweaker.Fluid;
import mods.contenttweaker.Color;

val zsFluid = VanillaFactory.createFluid("zs_fluid", Color.fromHex("FF69B4"));
zsFluid.fillSound = <soundevent:block.anvil.place>;
zsFluid.luminosity = 15;
zsFluid.stillLocation = "minecraft:blocks/water_still";
zsFluid.register();
```

![2018-09-16_00 02 49](https://user-images.githubusercontent.com/28705167/45587673-f3db8f00-b943-11e8-945f-8d640bd83b67.png)
I changed the texture of fluid in this picture, but I made sure that default texture shows fine.
