### ISSUE TITLE
infinite fluid suply has same recype as water one

### ISSUE THREAD

**Issue by DarkShadow012** [Kotori316/FluidTank#111]
how could i make a recype to give me fluid suply instead of water?

**Comment by Kotori316** [comment]
In default, the Infinite Fluid Supplier is not craftable. JEI will show a recipe for the block, but it is for Infinite Water Supplier.

Infinite Fluid Supplier is now creative-only block unless you add your own recipe. Here is an example recipe definition. You  need to add this recipe into your environment if you want to make Infinite Fluid Supplier craftable. Don't ask me how to add recipe, because there are a lot of material for this kind of question.
```json
{
  "type": "minecraft:crafting_shaped",
  "category": "misc",
  "key": {
    "I": {
      "tag": "forge:storage_blocks/iron"
    },
    "d": {
      "item": "minecraft:diamond"
    },
    "g": {
      "tag": "forge:ingots/gold"
    },
    "i": {
      "tag": "forge:ingots/iron"
    },
    "w": {
      "item": "minecraft:water_bucket"
    }
  },
  "pattern": [
    "wiw",
    "gIg",
    "wdw"
  ],
  "result": {
    "item": "fluidtank:fluid_source",
    "nbt": {
      "unlocked": true
    }
  }
}
```
