### ISSUE TITLE
Contrast of liquids function of time of the day [1.15.2]

### ISSUE THREAD

**Issue by Rictu5** [Kotori316/FluidTank#45]
The liquids stored in the tanks have a different contrast depending of the time (during the minecraft day).

![2020-04-13_14 40 44](https://user-images.githubusercontent.com/31549317/79121304-45a10100-7d95-11ea-9ed9-80ddc0f34bf1.png)
![2020-04-13_14 40 54](https://user-images.githubusercontent.com/31549317/79121311-48035b00-7d95-11ea-924a-6a7685bcc354.png)

Forge : 31.1.27
LargeFluidTank : 15.2.3

**Comment by Kotori316** [comment]
Noon
![2020-04-15_20 43 55](https://user-images.githubusercontent.com/28705167/79333850-30290400-7f5a-11ea-8b37-0d11151a9145.png)

Mid Night
![2020-04-15_20 43 44](https://user-images.githubusercontent.com/28705167/79333869-37e8a880-7f5a-11ea-9394-15bf1bd1a9ec.png)

This issue will be fixed in v15.2.5
I'll soon upload new file on CurseForge.
