### ISSUE TITLE
Game crash breaking tank with fluid inside

### ISSUE THREAD

**Issue by Astewen** [Kotori316/FluidTank#5]
I was testing the mod (LargeFluidTank-2.1.jar) and built 8 wood tanks and used them to make 2 iron tanks. I loaded some liquid (creosote from IE) into one tank and piped it into an adjacent tank using an Ender IO Pressurized Fluid Conduit. When I broke the tank that received the fluid I got a game crash:

java.lang.ClassCastException: net.minecraft.item.ItemAir cannot be cast to com.kotori316.fluidtank.items.ItemBlockTank

Full crash log here: https://pastebin.com/SHBN8pLx

Now I cannot load that world at all, the game crash is repeated on load. Fortunately I always make a backup before testing a mod so I can restore it back to where it was. Please let me know when fixed... this mod looks promising!

**Comment by Kotori316** [comment]
Thank you for your report. This crash was caused by Botania. According this [page](https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/api/BotaniaAPI.java#L366), the count of new ItemStack is 0, which makes the stack empty. The method "getItem" returns Items.Air if the stack is empty. Then ClassCastException happens.
I fixed my code and checked "Greater Ring of Magnetization" worked fine.

You can find the new version, "LargeFluidTank-2.2.jar", [here](https://drive.google.com/drive/folders/1YDorkQXeQbekJ33b-YqHs3HmhC4NL0OG).
