### ISSUE TITLE
[1.16.5] Tanks used in custom recipes are not consumed when there is liquid inside. (Dupe)

### ISSUE THREAD

**Issue by Freebi85** [Kotori316/FluidTank#84]
Hey there! 😃 

Not sure if this is related to https://github.com/Kotori316/FluidTank/issues/83 or if you are interested in changing something here, but whenever i use fluid tanks as input item for custom recipes (using kubejs or crafttweaker) the tanks gets only consumed when there is no liquid inside. Tanks with a liquid remain in the crafting grid even though the output item of the recipe has already been produced. This ends depending on the custom recipe in a dupe.

Cheers

**Comment by Freebi85** [comment]
Hm, well i found a workaround with crafttweaker using the replace functions.
`.transformReplace(<item:minecraft:air>)`

This always consumes the tank no matter if with liquids or not. I guess i can live with that.

Cheers

**Comment by Kotori316** [comment]
This behavior is intended.
Considering a recipe that consumes fluid in bucket, such as creating Treated Wood in IE and creating Cooling Cell in IC2, the bucket itself shouldn't be consumed and only the content should be consumed.
Related issue is #49 

Actually vanilla recipe can cause the same problem. I added recipe to create lava bucket from 1x Water Bucket and 1x Magma Block. After crafting, the bucket is duplicated, as empty bucket remains in the ingredient slots. The problem is here. You have to remove remaining item after crafting if you want to update tank or creating other fluid container. In vanilla, there are no way to do so, but as you found, CraftTweaker and KubeJS provide the option.
![2021-10-22_12 08 50](https://user-images.githubusercontent.com/28705167/138387932-e9847b07-4853-496c-8817-4c8a18fdaf7e.png)

Recipes to upgrade tanks in my mod keep the content, but they use my custom recipe class, which can be realized only in mods.
